FROM ros:noetic-ros-base-focal as base

ENV TZ=Europe/Warsaw
RUN ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime
RUN echo "$TZ" > /etc/timezone

# -----> DEPENDENCIES <-----
RUN apt-get update
RUN apt-get install -y tzdata
RUN apt-get install g++ -y && apt install git -y && apt install vim -y && apt install g++ -y && apt install build-essential -y
RUN apt-get install build-essential cmake -y --no-install-recommends 
RUN apt-get install libboost-all-dev -y
RUN apt-get install apt-utils gdb nano -y

# joy
RUN apt-get install ros-noetic-joy -y
# can
RUN apt-get install can-utils kmod udev net-tools -y
# xsens
RUN apt-get install ros-noetic-tf2* -y 
RUN apt-get install sharutils -y
RUN apt-get install ros-noetic-xacro -y

# -----> TELEMETRY <-----

RUN apt-get install -y tzdata
RUN apt-get install g++ -y && apt install git -y && apt install vim -y && apt install g++ -y && apt install build-essential -y
RUN apt-get install build-essential cmake -y --no-install-recommends 
RUN apt-get install libboost-all-dev -y
RUN apt-get install apt-utils libprotobuf-dev -y
RUN apt-get install curl libssl-dev libcurl4-openssl-dev -y
RUN apt-get install libfmt-dev -y
RUN sudo apt-get install -y libsnappy-dev
RUN apt-get install gdb kmod can-utils net-tools udev -y

RUN git clone https://github.com/jupp0r/prometheus-cpp.git
WORKDIR prometheus-cpp
RUN git submodule init
RUN git submodule update --recursive
RUN cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_PUSH=OFF -DENABLE_COMPRESSION=OFF /prometheus-cpp
RUN cmake --build .
RUN cmake --install .

WORKDIR /
RUN git clone https://github.com/mircodezorzi/loki-cpp.git
WORKDIR loki-cpp
RUN mkdir build && cd build
WORKDIR /loki-cpp/build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release
RUN cmake --build .
RUN cmake --install .

WORKDIR /
RUN git clone https://github.com/fmtlib/fmt.git
WORKDIR fmt
RUN mkdir build && cd build
WORKDIR /fmt/build
RUN cmake ..
RUN make
RUN make install

WORKDIR /

# -----> SETUP CONTAINER ON BOOT <-----
COPY /setup_joy.sh /
COPY /setup_can.sh /
COPY /entrypoint.sh /

RUN chmod +x /setup_joy.sh
RUN chmod +x /setup_can.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]


