version: '3.3'
services:
    putm_dv:
        build: .
        container_name: putm_dv
        image: putm_dv
        privileged: true
        volumes:
            - '/dev:/dev'
            - '$PWD/catkin_ws/:/home/putm/catkin_ws'
            - '/lib/modules:/lib/modules'
            - '/run/udev:/run/udev:ro'
        network_mode: host
        restart: always
